---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1v0ycqzd5rg2cvg8yes6me2tfcg6356f46ww2qfyqglj6gufnt5nq99eu6y"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1v0ycqzd5rg2cvg8yes6me2tfcg6356f46ww2qfyqglj6gufnt5nq99eu6y"
stores:
  yaml:
    indent: 2
