apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xxp7LJ0ohqw+C3JpMQ==,iv:C7gWMoGK6c1gjQ88rBFiww4U1BFbh+Nj22yeI8hm8jc=,tag:IKrs7Q+wk2T9PTd2iOjYHQ==,type:str]
sops:
  age:
    - recipient: age1v0ycqzd5rg2cvg8yes6me2tfcg6356f46ww2qfyqglj6gufnt5nq99eu6y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMmdrL2F1UDRLVVVGZmdl
        Q1pCN014aVBKVXgyU3pHMzdWZ0o0cFB0R3dzCklNQ1B4akZ0QU54OVhqRlhVdFlK
        TVp1RnBiUHlISzdKdjErNzIxQUQ1bTAKLS0tIHgxUmVvaTI1UWY3c1lrZ3NSTzF4
        amtCWklBMzJ4YThNNU5weDJDd3FpalkKEvNF6uDhRAmJXl6hlR3tJ+Shq+PrV+Q6
        0dp7C9m4rwNZOVIxnNrnuP3uqNezrnnyLC05gLCeKvMnhz66V66n+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-27T22:51:38Z"
  mac: ENC[AES256_GCM,data:VKCWrvT9Kx7u3X3KIAclk5LSIynxGd9ZHMVmC3TaNsjJbmBSXFHuSOYX+gpPJ9d5XmMihY19gkT70IrRxTzPltNMI9MOznFrO+nDRvVPkKZtBvF6hNK00SCWXDCNB1+fDu4TAwfln7FripSEIR/Q5sPvrDeRybgQdTIef8CjXhQ=,iv:CIHsG9nyjKg6LU4EEefMtyANdtavQ8tZBjSGfLIxSDY=,tag:0Q600/hQHsQmfGts811smA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
